// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestTGDDsearchTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testTGDDsearch() {
    driver.get("https://www.thegioididong.com/");
    driver.manage().window().setSize(new Dimension(1552, 880));
    driver.findElement(By.id("skw")).click();
    driver.findElement(By.id("skw")).sendKeys("iphone");
    driver.findElement(By.id("skw")).sendKeys(Keys.ENTER);
    {
      WebElement element = driver.findElement(By.cssSelector(".item:nth-child(1) .item-img > img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".item:nth-child(1) .item-img > img")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,56.79999923706055)");
    driver.findElement(By.cssSelector("button > .icon-search")).click();
    driver.findElement(By.cssSelector("button > .icon-search")).click();
    driver.findElement(By.cssSelector("button > .icon-search")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("button > .icon-search"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("button > .icon-search")).click();
    driver.findElement(By.id("skw")).click();
    driver.findElement(By.id("skw")).sendKeys("iii");
    driver.findElement(By.cssSelector("button > .icon-search")).click();
    driver.findElement(By.cssSelector("button > .icon-search")).click();
    driver.findElement(By.id("skw")).click();
    driver.findElement(By.id("skw")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("skw")).sendKeys("iii");
    driver.findElement(By.id("skw")).click();
    driver.findElement(By.cssSelector(".header__address")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".header__address"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Hà Nội")).click();
    driver.findElement(By.linkText("Quận Hà Đông")).click();
    driver.findElement(By.linkText("Phường Phú Lương")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".item:nth-child(5) .thumb"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
